language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sazzadrupak/react-test -f ./front/Dockerfile.dev ./front

script:
  - docker run -e CI=true sazzadrupak/react-test npm run test

after_success:
  - docker build -t sazzadrupak/multi-client ./front
  - docker build -t sazzadrupak/multi-nginx ./nginx
  - docker build -t sazzadrupak/multi-server ./server
  - docker build -t sazzadrupak/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sazzadrupak/multi-client
  - docker push sazzadrupak/multi-nginx
  - docker push sazzadrupak/multi-server
  - docker push sazzadrupak/multi-worker
